### ISSUE TITLE
another alternative solution: use importmap

### ISSUE THREAD

**Issue by SimonHeimberg** [keller-mark/dynamic-importmap#6]
I suggest to add another alternative to README.md.

Since ~2022, most browsers support importmaps (older ones are supported with the ES Module Shims import maps polyfill).
```html
<script type="importmap">
{
  "imports": {
    "lit": "https://ga.jspm.io/npm:lit@3.1.4/index.js"
  }
</script>
```
The module can be imported as `lit` now.

To manage importmap, I found jspm .
https://jspm.org/faq

More tools: https://github.com/WICG/import-maps?tab=readme-ov-file#community-polyfills-and-tooling

**Comment by keller-mark** [comment]
This package is motivated by the situation when regular importmaps cannot be used. Please see the motivation section https://github.com/keller-mark/dynamic-importmap?tab=readme-ov-file#motivation

**Comment by SimonHeimberg** [comment]
True, I see this in motivation. But I definitely got lost in the example of the problem. It looks like my technical understanding is not sufficient.
I guess jspm is an example of pre-writing-solution (https://github.com/keller-mark/dynamic-importmap?tab=readme-ov-file#pre-rewriting-solution), but guess only.

Thank you
